### ISSUE TITLE
Can't Compile or Copy to a Connected Tablet

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#11]
Sanny can see the removable DVD drive, but can't seem to access the connected tablet at all. I was hoping to compile and copy directly to the game folder but can't find the device.

**Comment by x87** [comment]
Can you explain more: "can't find the device". Is it not accessible to set as a game folder in the options, you can't save a file using File->Save menu, or the compiler fails to make a file after compilation is done? 

I personally tested Sanny on an external SSD drive connected via USB and everything seems to work fine. Can you also check if the folder you are trying to reach is not read-only?

**Comment by OrionSR** [comment]
I can find my tablet using the File Open menu, save, and compile to that folder. I would prefer to keep my text scripts on my PC and use Compile and Copy to move only the script version I intend to use.

The dialog for setting the install directory used for Compile and Copy does not list the device.
File Save As uses a UI similar to File Open but does not list the connected tablet.

**Comment by x87** [comment]
@OrionSR 
now that we could change the directory for Compile+Copy option (see #48), can you check if providing a direct path to the remote device does help?

**Comment by OrionSR** [comment]
No, I still can't compile and copy to my tablet, but I'm pretty sure that's by design. SB appears to have the same capabilities and limitations as any other app. The only notable difference, 010 marked files opened from the tablet as read only; or perhaps it knew that that cached folder was read-only or invalid. 

I'm convinced that Windows 10 is not going to let me compile and copy to my old Android tablet using the standard tools. I can't really generalize to similar or modern devices. Apps can open cached copies of the tablet's files but can't save to the device.
