### ISSUE TITLE
High-level code limitation [BUG]

### ISSUE THREAD

**Issue by b13ck** [sannybuilder/dev#114]
`{$CLEO}
0000:

while true
wait 0
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0
then
else
if 1@ == 0   // IF MORE BUG, WE CAN'T COMPILE SCRIPT :(
then
else
if 1@ == 0
then
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end
end 
`
Please Fix it

**Comment by x87** [comment]
@b13ck thanks for reporting the issue. There was an overflow in one place, I've fixed it.
