### ISSUE TITLE
EAccessViolation when attempting to compile via CLI

### ISSUE THREAD

**Issue by VitalRus95** [sannybuilder/dev#117]
When I try to compile a small code (.txt) to **.cs** using command line in Sanny Builder, I get “_Access violation_” error.

### Error screenshot:
![SB_error](https://user-images.githubusercontent.com/73489604/102822738-a8e63700-43ea-11eb-80e9-b8039261e8ff.PNG)

### Script source code:
```
{$CLEO .cs}
    0000:
    repeat
    wait 0
    until player.Defined(0)
    player.Money(0) += 500
    018C: play_sound 1054 at 0.0 0.0 0.0
    0A93: terminate_this_custom_script
```

This source file can be compiled perfectly fine if manually open in SB. But when it is compiled through CLI, the resulting .cs gets somehow corrupted: the script actually works in the game but its decompiled code is full of some trash:
[PyTest.txt](https://github.com/sannybuilder/dev/files/5726594/PyTest.txt)

### Additional information:
- Tested on SB ver. **3.6.2** and **3.5.1**.
- Launched in **.py**, **cmd**, and **sanny.exe shortcut**.
- Launching as **admin** didn't help.
- The launch command in the **shortcut** is the following: `"C:\Program Files (x86)\Sanny Builder 3\sanny.exe" -m sa --no-splash -c "D:\Games\GTA SA\CLEO\PyTest.txt" "D:\Games\GTA SA\CLEO\PyTest.cs"`.
- Attempting to compile with SB v3.6.2 installed on `D:` drive yielded the same result.
- Attempting to compile from .txt with **UTF-8 with BOM** encoding results in this absurd: 
[PyTest.txt](https://github.com/sannybuilder/dev/files/5726641/PyTest.txt)

Me and @wmysterio have struggled with this problem for some time but we didn't manage to find a solution yet. Thanks for any help!

**Comment by x87** [comment]
@VitalRus95 Confirming this bug. 

As a workaround add `{$NOSOURCE}` at the top of your script and it should compile.

**Comment by wmysterio** [comment]
I tested with `{$NOSOURCE}`. SB saved file with encoding `ASCII` (maybe). If convert this file to `ANSI` or `UTF-8 without BOM` then compiling complete successfully.

If file have `UTF-8 (with BOM)` encoding, SB generate `compile.log` file with text: `error: Неизвестная команда п»ї{$CLEO .cs}`. I expected this.

My SB do save source `*.txt` with normal encoding. I don't know why Vital's SB saved file with incorrect encoding. Maybe it is user settings or fortuity. Need answer from @VitalRus95 .

**Comment by VitalRus95** [comment]
> 
> 
> I tested with `{$NOSOURCE}`. SB saved file with encoding `ASCII` (maybe). If use his or convert this file to `ANSI` or `UTF-8 without BOM` then compiling/decompiling complete successfully. Need answer from @VitalRus95 .
> 
> Vital's file generate `compile.log` with `error: Unknown command п»ї{$CLEO .cs}`. This is typical when use `UTF-8 (with BOM)` encoding. Need try to teach SB to save the source in the desired encoding so as not to use `{$NOSOURCE}` unnecessarily.

Yes, both Python and SB generate .txt with UTF-8 (without BOM) encoding (as indicated in Notepad++). Yet manually it can be both compiled and decompiled without any issues and without `{$NOSOURCE}`.

**Comment by VitalRus95** [comment]
> 
> 
> @VitalRus95 Confirming this bug.
> 
> As a workaround add `{$NOSOURCE}` at the top of your script and it should compile.

`{$NOSOURCE}` works nice! No error is thrown, the script gets compiled and decompiled fine. Thanks a lot for this suggestion, I hope it won't be too difficult to eliminate the bug in future versions of SB! Good luck!
