### ISSUE TITLE
NEW FEATURE: Zoom into the letters.

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#122]
### Increase and decrease the size of the letters
Many of us are very often changing the size of the letters and others may not, but this is something that most IDEs carry and it would be a very good thing if they included the SB.
The idea of ​​the controls for this would be the standard

* `Ctrl` + `Scroll of Mouse`

| Ctrl + | Scroll Up |Scroll Down |
| -------| ---------- |------------- |
|           | Zoom in  | Zoom out |

it is true, if it is in the documentation, with this configuration

| Text / Navigation | |
| ------------ |----- |
| `Ctrl+ScrollUp` `Ctrl+ScrollDown` | page up / down |
| `Ctrl+Num+` `Ctrl+Num-` | zoom in / out |

But there is already a button to do Page Up and Page Down, and in laptops that do not have that button, it is done with the combination of the buttons <Function> e.g.
* `Fn` + `ArrowUp` = Page Up
* `Fn` + `ArrowDown` = Page Down

so the current combination is a bit obsolete.
Or else, how about this other?
# Support custom controls
This would be a very useful functionality, since it allowed to adapt the tastes of the community with great comfort, so they would no longer have to use third-party programs for their projects.

> Of topic #60

**Comment by x87** [comment]
`Ctrl` + `+`
`Ctrl` + `-` 
these should be more common, at least this is what browsers do where I use this feature often.

**Comment by MatiDragon-YT** [comment]
oh... I thought that browsers only supported Ctrl + Scroll, like the vast majority of photo editors.
> incredible that data, although I went more for the standard of the IDEs and not the Internet browsers. Still, I appreciate you answering my tickets/topics ;)

**Comment by x87** [comment]
As of v3.8.0 the hotkeys for zooming in and out are Ctrl+ and Ctrl-
