### ISSUE TITLE
NEW FEATURE: Compile new opcodes.

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#127]
Wouldn't it be great if SB could compile its own cleo libraries in the same IDE?
> Yes, I know.. I'm a little crazy... 

I know that making a compiler is a bit complicated, but it would be very nice if SB had support for this and I am not saying that they add it right now or that they give high priority to this ticket/topic.
The idea arose from the high consumption of resources that VS and VSC have with the long time that we have to wait for the program to finish launching.
I also thought that if to make a CleoScript you always have to use the directive `{$CLEO}`, then for a library, you could use `{$SDK}`, or some header like `using sdk` to be able to differentiate a library from  a script.
Although to get to all this, I think that first you would have to implement a project system, mentioned in ticket/topic #126

**Comment by x87** [comment]
No, I'm not going to implement C++ compiler or even try to write some minimal support for this language. You can run a C++ compiler from terminal without any IDE be feeding in some input .cpp files and you don't need VS or VSC for that. You can even do that from Sanny if you provide correct input parameters in User tools.

IDE support for C++ language is nowhere possible and I'm not capable of doing that. I'm pretty sure there are lightweight editors for C++ outside of VS/VSC.
https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#C/C++
