### ISSUE TITLE
Constant syntax highlighting doesn't work (associated files)

### ISSUE THREAD

**Issue by wmysterio** [sannybuilder/dev#131]
If you open a file that is associated with SB and the compiler is not running, the constants are not highlighted. The problem was noticed and confirmed by two people. Is this a bug or should it be?

**Comment by x87** [comment]
@wmysterio Hi. Can you describe in detail how to reproduce the issue? I have ***.scm** and ***.cs** files associated with SB and when I open them (disassemble), the highlighting is working. Can you make some screens or record a video for me, please?

**Comment by wmysterio** [comment]
@x87 https://youtu.be/K8or68cmO-w

**Comment by x87** [comment]
Try with this updated core.dll. Place it in `Sanny Builder\lib` folder.
[core.zip](https://github.com/sannybuilder/dev/files/5963298/core.zip)

**Comment by wmysterio** [comment]
Good. It is working.
