### ISSUE TITLE
NEW FEATURE: See opcode at gtagmodding.com

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#132]
As we know, in the lower left corner, we have a box that indicates the number of parameters to be entered in an opcode.

What if it becomes a kind of dynamic button, which when pressed redirects us to gtagmodding.com to see more information about the opcode we are working on?

This new feature It would be quite useful, like the online help button that appears in the Compilation Error Alerts.

click on:
[XXXX: x parameters]
for open:
https://gtagmodding.com/opcode-database/opcode/XXXX/

**Comment by x87** [comment]
Thanks for your idea. Yes, I was going to add opcode descriptions in one of the future versions. My goal is to make a complete commands database that Sanny can download as a single file and then use to display the descriptions. Adding a button to see extra information on GTAG or GTAMods.com would also be useful 👍 

current progress can be seen at https://github.com/sannybuilder/library

**Comment by MatiDragon-YT** [comment]
So could this option be implemented until the other database is finished?

**Comment by MatiDragon-YT** [comment]
We already have SB Library 😎

https://library.sannybuilder.com/
