### ISSUE TITLE
Constants are not Highlighted Recursively

### ISSUE THREAD

**Issue by HzanRsxa2959** [sannybuilder/dev#134]
![Sanny Builder 3 3_8_2021 10_21_56 AM](https://user-images.githubusercontent.com/64904356/110278049-546d5380-7ff8-11eb-9788-9437c0b2b6d6.png)

As you can see, 'b' does not get its color from 'a', while 'a' get its color from its value.

Test on 3.7.0, released 2021-1-30.

**Comment by x87** [comment]
Updated core.dll for v3.8.5 with recursive highlighting is available here
https://github.com/sannybuilder/core/issues/12#issuecomment-1546686072
