### ISSUE TITLE
Critical error in enum interpreter.

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#139]
The error does not allow the IDE to read the enumeration and the rest of them properly.
It only appears when you use a word that contains `end`
```haskell
enum Example
	Matias=0				// Nice
	Girlfriends=184				// ERROR
	FriendlyGang=240			// ERROR
	BestPositionInCountryEndurance=286	// ERROR
	BestTimeInCountryEndurance=287		// ERROR
end
```
Small expression regex like this `\nend\n` might help :D

**Comment by x87** [comment]
@MatiDragon-YT please test with the dll from the attached archive. unzip to the Sanny Builder\lib folder.

[core.zip](https://github.com/sannybuilder/dev/files/6380120/core.zip)

**Comment by MatiDragon-YT** [comment]
With my files in `<sb>\data\sa`  [sa.zip](https://github.com/sannybuilder/dev/files/6385241/sa.zip)

I found two errors:
1. The first and most noticeable to the naked eye, the enumeration disables the number highlighter.
2. When wanting to compile with and without enums, the error below skips.
![image](https://user-images.githubusercontent.com/43966706/116256625-bd945c00-a749-11eb-8558-a0b1d09a4654.png)

**Comment by MatiDragon-YT** [comment]
With my files in `<sb>\data\sa`  [sa.zip](https://github.com/sannybuilder/dev/files/6385241/sa.zip)

I found two errors:
1. The first and most noticeable to the naked eye, the enumeration disables the number highlighter.
2. When wanting to compile with and without enums, the error below skips.
![image](https://user-images.githubusercontent.com/43966706/116256625-bd945c00-a749-11eb-8558-a0b1d09a4654.png)

**Comment by x87** [comment]
Hey @MatiDragon-YT thanks for the detailed report.

I'm able to reproduce the exception on v3.7.0 with the files you provided. However it works fine on my latest dev build. It appears as if something was broken, it has been fixed already. I will investigate and get back to you.

Regarding the numbers highlighting, it looks like you've encountered this bug: #129

**Comment by MatiDragon-YT** [comment]
@x87  A few weeks ago, I had a problem with SB, that when you ran it, it would jump a problem with the C ++ 2015 framework.
The error message was that it could not find a file `xxxxxx140.dll`.

Could you add a message to tell you that you have to install the x86 version?
SB does not recognize x64.  And there are people who stayed in v3.3.3 and 3.4.x why they did not know how to solve it.



Could all these problems be related to the c ++ framework?

**Comment by x87** [comment]
I'm not aware of this problem. Was it `msvcp140.dll` or `vcruntime140.dll`?

**Comment by MatiDragon-YT** [comment]
Exactly `vcruntime140.dll`

**Comment by x87** [comment]
Are you able to reproduce this error again by uninstalling Microsoft Visual C++ Redistributables or by deleting `vcruntime140.dll` from your PC? I want to test if the attached DLL has no dependency on C++ runtime.

[core_static.zip](https://github.com/sannybuilder/dev/files/6386041/core_static.zip)

**Comment by MatiDragon-YT** [comment]
**sanny.exe - System error**
Code execution cannot continue because `vcruntime140.dll` was not found. 
![image](https://user-images.githubusercontent.com/43966706/116278687-1e795f80-a75d-11eb-9b1b-10d792077ea5.png)
if you install `Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215` the error disappears

**Comment by x87** [comment]
Is this happening even with core.dll from static zip?

**Comment by MatiDragon-YT** [comment]
Yes yes...

**Comment by x87** [comment]
Ok, I'll take a look. Thanks for letting me know 👍

**Comment by x87** [comment]
@MatiDragon-YT please try with updated DLL from the attached archive. unzip to sanny builder\lib folder.

[lib_static.zip](https://github.com/sannybuilder/dev/files/6446824/lib_static.zip)

**Comment by MatiDragon-YT** [comment]
These new libraries work well :') 👍
