### ISSUE TITLE
Occasional app crashes when Language service is disabled

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#146]
Yes, it keeps happening in 3.8.0. I would willingly share the .log, but I don't have one near sanny.exe, unfortunately. All I have is these three errors at the same time:
![изображение](https://user-images.githubusercontent.com/73489604/121264868-870d3d80-c8c0-11eb-8c0f-aae258d387e9.png)
When I close them, SB loads and works like nothing happened.

_Originally posted by @VitalRus95 in https://github.com/sannybuilder/dev/issues/130#issuecomment-857215589_

**Comment by x87** [comment]
@VitalRus95 this does not look like a valid address in v3.8.0-alpha.1 Also the settings.ini you attached are from an older version (no theme reference).

Can you reproduce the error on the latest version and tell me the address where it crashes?

**Comment by VitalRus95** [comment]
It seems the issue is resolved now! I installed 3.8.0 alpha 2 and launched SB like 15 times in a row without errors, thank you very much for fixing this!
