### ISSUE TITLE
Disassembler can't properly handle classes with variadic arguments

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#149]
When the IDE comes across an OPCODE that contains a function like REST / CALLBACK (`XXXX=-1,[...]`), the opcode class goes crazy. The IDE copies and pastes the last value entered in the opcode, until the 35 spaces it allows are completed.
That is to say that from this:
```js
Memory.CallFunction(0@, 1@, 2@, 3@)
```
becomes this:
```js
Memory.CallFunction(0@, 1@, 2@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@, 3@)
```
There are times when it does not copy the last value, but 2 values at the same time.
You could include a parameter like `% r` to represent a REST / CALLBACK and prevent that error
```bash
; example
CallFunction, 0AA5,0,0, ("address% i" "numParams% i" "pop% r")
```

_Originally posted by @MatiDragon-YT in https://github.com/sannybuilder/dev/issues/66#issuecomment-857796600_

**Comment by x87** [comment]
@MatiDragon-YT this issue should be fixed in https://github.com/sannybuilder/dev/releases/tag/v3.8.0-alpha.3

**Comment by x87** [comment]
@MatiDragon-YT Have you tried the new version? Do you still experience this issue?

**Comment by MatiDragon-YT** [comment]
@x87 you are the coolest magician I have ever seen :)

I downloaded it yesterday and see the problem no longer exists.

**Comment by MatiDragon-YT** [comment]
@x87 I ran into some new problems wanting to make some classes decompile like this:
```js
0@ = Xx.XxxxXxxx(3@v, "%d + %d", 1@, 2@)
```
and i got these results with these settings...
```js
XxxxXxxx,[XXXX,=,2,2,0],(...)   ->   Xx.XxxxXxxx(0@, 3@v, "%d+%d", 1@, 2@)
XxxxXxxx,[XXXX,=,2,1,0],(...)   ->   0@ = Xx.XxxxXxxx(3@v, "%d+%d", 1@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@)
XxxxXxxx,[XXXX,=,2,0,0],(...)   ->   0@ = Xx.XxxxXxxx(3@v, "%d+%d", 1@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@)
```
---
I could also notice that the strings were being poorly compiled.
Here is a fragment of code with which I was doing tests and the files of the SA mode that I have modified.
[sa.zip](https://github.com/sannybuilder/dev/files/6727717/sa.zip)
```ini
{$CLEO}
const
numParams = 0@
stringVar = 3@v
charSame = 0x3D { = }
end
nop
    repeat
        wait 0
    until Input.IsKeyPressed(VK.O)
    
    string_format stringVar = "%d * %d" 4 10  // 4 * 10
    
    if//                           (stringVar == "\d + \d")                 
        numParams = Text.ScanString(stringVar,   "%d + %d", 1@, 2@)
    then
        Text.PrintHelpString("Performing addition...")
        0A8E: numParams = 1@ + 2@
        wait 2000
        Text.PrintHelpFormatted("%d + %d %c %d", 1@, 2@, charSame, numParams)
    end
    if
        numParams = Text.ScanString(stringVar,  "%d * %d", 1@, 2@)
    then    
        Text.PrintHelpString("Performing multiplication...")
        0A90: numParams = 1@ * 2@
        wait 2000
        Text.PrintHelpFormatted("%d * %d %c %d", 1@, 2@, charSame, numParams)
    end
terminate_this_custom_script
```

**Comment by x87** [comment]
@MatiDragon-YT 

>I could also notice that the strings were being poorly compiled.

can you clarify the issue? What is the compiler error?

**Comment by MatiDragon-YT** [comment]
> @MatiDragon-YT
> 
> > I could also notice that the strings were being poorly compiled.
> 
> can you clarify the issue? What is the compiler error?

the values `STRING`.
Are delete the White Spaces

**Comment by x87** [comment]
Sorry, I didn't get you. You mean the compiler stripped whitespaces from the string literal?

What `STRING` is referred to

**Comment by MatiDragon-YT** [comment]
> Sorry, I didn't get you. You mean the compiler stripped whitespaces from the string literal?
 
YES, YEEESSS..
For example `Text.ScanString` & `Text.PrintHelpFormatted`

Sorry... my English is getting a bit bad from studying other languages :(

**Comment by x87** [comment]
I think what you describe is this issue: #66

**Comment by x87** [comment]
> 
> 
> @x87 I ran into some new problems wanting to make some classes decompile like this:
> 
> ```js
> 0@ = Xx.XxxxXxxx(3@v, "%d + %d", 1@, 2@)
> ```
> 
> and i got these results with these settings...
> 
> ```js
> XxxxXxxx,[XXXX,=,2,2,0],(...)   ->   Xx.XxxxXxxx(0@, 3@v, "%d+%d", 1@, 2@)
> XxxxXxxx,[XXXX,=,2,1,0],(...)   ->   0@ = Xx.XxxxXxxx(3@v, "%d+%d", 1@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@)
> XxxxXxxx,[XXXX,=,2,0,0],(...)   ->   0@ = Xx.XxxxXxxx(3@v, "%d+%d", 1@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@, 2@)
> ```

this issue should be gone with v3.8.0-beta.0, please try

**Comment by MatiDragon-YT** [comment]
Sure enough, the error disappeared.
