### ISSUE TITLE
Strategy for Refreshing games.xml

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#15]
I can manage different games.xml files with User Tools and Shortcuts but I can't find a way to get Sanny to load the updated file without restarting the program. I was hoping to find a quick way to switch between different command profile sets but came up just a tad short.

**Comment by x87** [comment]
How often this file needs to be changed though? Can you provide a use case when you need to update it not leaving the tool?

**Comment by OrionSR** [comment]
I am currently managing 4 games.xml files:
* GTA - Sanny's standard edit modes and custom modes for extra versions installed 
* OSR - 14+edit modes specific to each game, platform and version
* F92 - 12 edit modes that support fastman92's script command definitions data set
* ALL - All games.xml data merged into a single set because I can't switch between them
+ Filtering for platforms, games type, projects

**Comment by OrionSR** [comment]
Example: 3rd Party support for a games.xml manager. Even then, a built-in tool for selecting different edit mode sets would be handy. But I'm trying to work with what I've got as best I can.  User tools and shortcuts just need a way to refresh.

**Comment by OrionSR** [comment]
A more specific suggestion:
```sanny.exe -x games.xml 
sanny.exe -x osr_games.xml 
sanny.exe -x osr\games.xml```
The first example would refresh the default games.xml. The other examples would load the specified file but Sanny would revert to the default games.xml on the next restart.

A similar strategy for settings.ini might be helpful in the context of a batch compilation process.
