### ISSUE TITLE
Constant as a class name

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#155]
I have a small suggestion, don't know if that's possible to implement, but it would be nice. I noticed that you can't call class commands from a constant. For instance, if you declare `3@` as an `Actor` and assign a constant `swt` to the value `3@`, then you can use
```
3@.Create(…)
```
yet you won't be able use
```
swt.Create(…)
```
The latter, I think, may make constants even more helpful in SB (again, if possible and reasonable).

_Originally posted by @VitalRus95 in https://github.com/sannybuilder/dev/issues/130#issuecomment-862735730_

**Comment by wmysterio** [comment]
Hmm, if such a record becomes available, is it possible to add the ability to specify the type in the `const-end` block?
```text
const
swt = 3@ : Actor
end

swt.Create(…)
```
Then it turns out that the `var-end` block is not needed at all :)
```text
var
3@ : Actor
end

const
swt = 3@
end
```

**Comment by x87** [comment]
@wmysterio this idea was already expressed in #32 . In short I'm not a fan of doing that as it makes very vague a difference between constants and variables. 
I'm in favor of the inline declaration as here: https://github.com/sannybuilder/dev/issues/37#issuecomment-749933613
