### ISSUE TITLE
Make IGNORE_UNKNOWN enabled by default

### ISSUE THREAD

**Issue by megapro17** [sannybuilder/dev#156]
Error `0016: Script not found` is happening even on unmodified 1.00 main.scm. So it's the game itself has problems. And sanny builder refuses to open it by default.

**Comment by megapro17** [comment]
It doesn't want to open it anyway and shows error `List index out of bounds (-66977788).`

**Comment by x87** [comment]
@megapro17 can you attach the main.scm/script.img here and tell me the version of Sanny Builder that you use?

error 0016 usually means that the script.img file was compiled with another main.scm. you can check if the file modification time is the same on both.

**Comment by megapro17** [comment]
I'm using 3.7.0 version.
[script.zip](https://github.com/sannybuilder/dev/files/6670547/script.zip)

**Comment by x87** [comment]
I can decompile this script using v3.7.0, so the issue must be on your end.

Make sure you have selected the correct mode in the bottom right corner. It should be one of the GTA SA modes
https://docs.sannybuilder.com/edit-modes#selecting-a-mode

**Comment by megapro17** [comment]
Wow, I spent so much time and didn't even noticed that switch.. thank you
