### ISSUE TITLE
Add or fix the support of functions placed in constants

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#163]
Sanny Builder currently no longer understands function [constants](https://docs.sannybuilder.com/coding/constants#syntax), making the information provided to users in the documentation obsolete:

```
const
    MoneyRequired = 30
    PlayerMoney = $PLAYER_CHAR.Money
end

if
    PlayerMoney > MoneyRequired   // ERROR 0068
then
    PlayerMoney += -1
end
```

these are also highlighted in the same color as the gosubs :)

**Comment by x87** [comment]
This example is missing the variable `$PLAYER_CHAR` declaration. The complete code should look like this:

```
var
   $PLAYER_CHAR: Player
end

const
    MoneyRequired = 30
    PlayerMoney = $PLAYER_CHAR.Money
end

if
    $PLAYER_CHAR.Money > 30
then
    PlayerMoney += -1
end
```

I will update the documentation.

**Comment by MatiDragon-YT** [comment]
and support this?
```
const
    test = Game.SetShowSaveScreen()
end

test
```

**Comment by x87** [comment]
This is not a use case for `const`.

Once we implement pre-processor directives (#144) you can #define any code as a macro.

define test 
  Game.SetShowSaveScreen()
end

test //or Game.SetShowSaveScreen()
