### ISSUE TITLE
Inline Variable Pointer

### ISSUE THREAD

**Issue by HzanRsxa2959** [sannybuilder/dev#173]
_IDK if this called 'inline' or not._

See this code:
`0AB1: cleo_call @setVar 1 110~0@`

The two new values:
1. `~`: Indicator to inline this variable's pointer.
2. `110`: Value of the variable set after passing its pointer. 0 if not set.

See these two examples:
1. `0AB1: cleo_call @setVar 1 110~0@`
2. `0AB1: cleo_call @setVar 1 ~0@`

They would be expanded to these before compilation:
1.
`0AC7: 0@ = var 0@ pointer`
`0AB1: cleo_call @setVar 1 0@`
`0@ = 110`
2.
`0AC7: 0@ = var 0@ pointer`
`0AB1: cleo_call @setVar 1 0@`
`0@ = 0`

**Comment by x87** [comment]
See https://github.com/sannybuilder/dev/issues/45#issuecomment-899088446
