### ISSUE TITLE
Issue in VC with model names when working with custom main.scm type.bug

### ISSUE THREAD

**Issue by Zarkong** [sannybuilder/dev#174]
Issue in VC, when working with custom main.scm, 
then popup model list didn't show correct, cargen model names crashed game and by decompiling the names were replaced with wrong numbers.
It doesn't happen with originally main.scm

Then i installed newest Sannybuilder version 3.8.0 and the issues were fixed

But it came back as i opened sanny the second time

Example:
The total stripped main below works fine
Then i add car generators
and want to get #ADMIRAL popup model list, but it's not available
the main.scm will crash
when i decompile the main.scm, the the model names were replaced with wrong numbers.

`DEFINE OBJECTS 1
DEFINE OBJECT (unused)                

DEFINE MISSIONS 0

//-------------MAIN---------------
03A4: name_thread 'MAIN' 
016A: fade 0 0 ms 
01F0: set_max_wanted_level_to 6 
0111: set_wasted_busted_check_to 0 
00C0: set_current_time 12 0 
04E4: unknown_refresh_game_renderer_at -372.8478 -535.991
03CB: set_camera -372.8478 -535.9914 17.2823 
0053: $PLAYER_CHAR = create_player #NULL at -372.8478 -535.9914 17.2823 
01F5: $PLAYER_ACTOR = create_emulated_actor_from_player $PLAYER_CHAR
0001: wait 1000 ms 

:MAIN_133 
00D6: if 
0256:   player $PLAYER_CHAR defined 
004D: jump_if_false @MAIN_133
01B6: set_weather 0 
0352: set_actor $PLAYER_ACTOR skin_to 'PLAYER' 
038B: load_requested_models 
0353: refresh_actor $PLAYER_ACTOR 
04BB: select_interiour 0 // select render area 
01B4: set_player $PLAYER_CHAR frozen_state 1 
01B7: release_weather
016A: fade 1 1000 ms

:MAIN_169
0001: wait 2500 ms 
0002: jump @MAIN_169`

Then i add car generators
 `DEFINE OBJECTS 1
DEFINE OBJECT (unused)                

DEFINE MISSIONS 0

//-------------MAIN---------------
03A4: name_thread 'MAIN' 
016A: fade 0 0 ms 
01F0: set_max_wanted_level_to 6 
0111: set_wasted_busted_check_to 0 
00C0: set_current_time 12 0 
04E4: unknown_refresh_game_renderer_at -372.8478 -535.991
03CB: set_camera -372.8478 -535.9914 17.2823 
0053: $PLAYER_CHAR = create_player #NULL at -372.8478 -535.9914 17.2823 
01F5: $PLAYER_ACTOR = create_emulated_actor_from_player $PLAYER_CHAR
0001: wait 1000 ms 

:MAIN_133 
00D6: if 
0256:   player $PLAYER_CHAR defined 
004D: jump_if_false @MAIN_133
01B6: set_weather 0 
0352: set_actor $PLAYER_ACTOR skin_to 'PLAYER' 
038B: load_requested_models 
0353: refresh_actor $PLAYER_ACTOR 
04BB: select_interiour 0 // select render area 
01B4: set_player $PLAYER_CHAR frozen_state 1 
01B7: release_weather
016A: fade 1 1000 ms
wait 2500
014B: 1@ = init_parked_car_generator #ADMIRAL -1 -1 1 alarm 0 door_lock 0 0 10000 at -348.47 -525.84 12.8 angle 98.1 
014C: set_parked_car_generator 1@ cars_to_generate_to 101 
014B: 2@ = init_parked_car_generator #sentxs -1 -1 1 alarm 0 door_lock 0 0 10000 at -348.47 -521.84 12.8 angle 98.1
014C: set_parked_car_generator 2@ cars_to_generate_to 101
014B: $1992 = init_car_generator #ADMIRAL 8 8 force_spawn 0 alarm 50 door_lock 0 min_delay 0 max_delay 10000 at -401.2715 -534.6655 11.7534 angle 149.2032 
014C: set_parked_car_generator $1992 cars_to_generate_to 101

:MAIN_169
0001: wait 2500 ms 
0002: jump @MAIN_169`

when i decompile the main.scm, the the model names were replaced with wrong numbers.
`// This file was decompiled using VCSCM.ini published on 2021-05-25
DEFINE OBJECTS 4
DEFINE OBJECT SANNY BUILDER 3.8.0     
DEFINE OBJECT NULL                     // Object number -1
DEFINE OBJECT ADMIRAL                  // Object number -2
DEFINE OBJECT SENTXS                   // Object number -3

DEFINE MISSIONS 0

//-------------MAIN---------------
script_name 'MAIN' 
fade 0 0 
01F0: set_max_wanted_level_to 6 
set_wb_check_to 0 
00C0: set_current_time 12 0 
04E4: request_collision_at -372.8478 -535.991 
Camera.SetAtPos(-372.8478, -535.9914, 17.2823)
Player.Create($PLAYER_CHAR, #NULL, -372.8478, -535.9914, 17.2823)
Actor.EmulateFromPlayer($PLAYER_ACTOR, $PLAYER_CHAR)
wait 1000 

:MAIN_94
if 
   Player.Defined($PLAYER_CHAR)
jf @MAIN_94 
set_weather 0 
0352: set_actor $PLAYER_ACTOR skin_to 'PLAYER' 
038B: load_requested_models 
0353: refresh_actor $PLAYER_ACTOR 
select_interior 0 
Player.CanMove($PLAYER_CHAR, True)
01B7: release_weather 
fade 1 1000 
wait 2500 
014B: 1@ = init_car_generator -2 -1 -1 force_spawn 1 alarm 0 door_lock 0 min_delay 0 max_delay 10000 at -348.47 -525.84 12.8 angle 98.1 
014C: set_parked_car_generator 1@ cars_to_generate_to 101 
014B: 2@ = init_car_generator -3 -1 -1 force_spawn 1 alarm 0 door_lock 0 min_delay 0 max_delay 10000 at -348.47 -521.84 12.8 angle 98.1 
014C: set_parked_car_generator 2@ cars_to_generate_to 101 
014B: $1992 = init_car_generator -2 8 8 force_spawn 0 alarm 50 door_lock 0 min_delay 0 max_delay 10000 at -401.2715 -534.6655 11.7534 angle 149.2032 
014C: set_parked_car_generator $1992 cars_to_generate_to 101 

:MAIN_306
wait 2500 
jump @MAIN_306 `

**Comment by x87** [comment]
@Zarkong do you have the game directory path set up in the options?
https://docs.sannybuilder.com/editor/options/general#game-directory

If yes, does it have any non-latin letters?

**Comment by x87** [comment]
closing as inactive
