### ISSUE TITLE
How do i import a cutscene from one GTA to another? 

### ISSUE THREAD

**Issue by LearnAllBoy** [sannybuilder/dev#178]
For example, i need to transfer the cutscene from GTA VC "Keep your friends close", to my own storyline in GTA SA, how do i make it play in my storyline? **What are the commands for that**?

P.S. : i've seen a san andreas based-on GTA LCS for PC, and there was a cutscene at first, how can i do it?

Thanks :)

**Comment by x87** [comment]
It's not related to Sanny Builder. I recommend you to seek an advice on dedicated message boards, such as gtaforums
