### ISSUE TITLE
⚙ Support for highlighting code from CLEO Redux

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#181]
## Custom Syntax
![1](https://user-images.githubusercontent.com/43966706/144733599-2980acd3-f590-4d54-9837-e490351052c2.png)

---

## Java Scripts
![2](https://user-images.githubusercontent.com/43966706/144733572-621a4a33-650f-4852-b116-17a40b3ed6a1.png)

**Comment by x87** [comment]
@MatiDragon-YT can you provide an example?

**Comment by MatiDragon-YT** [comment]
## Custom Syntax
![1](https://user-images.githubusercontent.com/43966706/144733599-2980acd3-f590-4d54-9837-e490351052c2.png)

---

## Java Scripts
![2](https://user-images.githubusercontent.com/43966706/144733572-621a4a33-650f-4852-b116-17a40b3ed6a1.png)

**Comment by x87** [comment]
Why would you want to edit .js files in Sanny Builder? Use VS Code for that

**Comment by MatiDragon-YT** [comment]
To have a higher performance.

On a low-resource PC type Dual Core 2.0GHz with 4 RAM, it is hardly possible to run VS Code, although the [web version](https://vscode.dev/) does have good performance. But it can only be accessed if you have internet.
Many prefer to use [Sublime Text](https://www.sublimetext.com/) as an alternative to this.

For these reasons I think it would be good to add these features to Sanny Builder and over time, maybe polish it with auto-completes and more...
