### ISSUE TITLE
Lowercase characters in long strings are being replaced by uppercase characters during compilation

### ISSUE THREAD

**Issue by NicusorN5** [sannybuilder/dev#185]
This is easily reproducible in my case. I just installed Sanny Builder (version 3.8.0) and VC.

This line of code
```0ADF: add_text_label "I_D1" text "~t~Cop 3~w~: So much for damn silence. Something new y'all three?"``` (this can be seen in the original .txt file)

compiles to:
```add_text_label "I_D1" text "~T~COP 3~W~: SO MUCH FOR DAMN SILENCE. SOMETHING NEW Y'ALL THREE?" ```
(as seen in the newly compiled .scm file in `<root>\data`.

This is obviously, not desired. And I want to avoid editing the GTX tables because of their limitations.

Hope will get a response ASAP, thank you.

**Comment by x87** [comment]
https://docs.sannybuilder.com/editor/options/formats#case-converting

**Comment by NicusorN5** [comment]
Oh my gosh, this is so stupid from me. Sorry, my bad.
