### ISSUE TITLE
⚠ SB cannot decompile and compile a main.scm (unmodified)

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#186]
![image](https://user-images.githubusercontent.com/43966706/155401381-e753ba46-c68a-45f3-b3d7-cad61b5d7351.png)
> I taked the capture with an unmodified SB 3.8.0

**Comment by NicusorN5** [comment]
Mind showing the original source so we can reproduce this issue?

**Comment by x87** [comment]
this is a known issue with the original main.scm in San Andreas. The solution for now is just remove all 4 lines after the label SYND4_3650

**Comment by MatiDragon-YT** [comment]
Would it be possible to create an error window with a code like 0090, to document it?

**Comment by x87** [comment]
Should be solved with #167

**Comment by x87** [comment]
New option for strict IF validation (disabled by default to allow recompiling original SA SCM) has been added in 4.0.0
