### ISSUE TITLE
⚠ Bug at Tools -> Make opcodes.txt

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#187]
Executing the option does not update the `opcodes.txt` file.

**Comment by x87** [comment]
Can you try running make_opcodes directly?
https://github.com/sannybuilder/make_opcodes

this is what Sanny Builder uses. Does this tool work for you?

**Comment by x87** [comment]
Maybe it is sensitive to the file names? Can you try running it from another directory?
Also try running as admin.

If you can share a video of you running it, it may help me to suggest further steps.

**Comment by MatiDragon-YT** [comment]
Sorry for the delay in responding.

I just tested it on two different terminals (GitBash and PowerShell) and at first neither worked with a cleo script source code. Then I tried it with the code that is generated by decompiling the main.scm of SA, and there if it worked, although I do not know well... I would say that in part... hahaha

Also I just noticed that there is no documentation about this tool in the CHM, it would be good to indicate that the tool cannot generate a complete list, if there are KEYWORDS or CLASSES in it.

But anyway, the tool still does not generate the list of opcodes if I run it from the IDE.

https://user-images.githubusercontent.com/43966706/188662389-f0e5cd68-61a0-49e4-b3ea-3f065c38347d.mp4

**Comment by x87** [comment]
>  it would be good to indicate that the tool cannot generate a complete list, if there are KEYWORDS or CLASSES in it.

it needs keywords list and/or classes.db to identify that a word is a keyword or a class (e.g. wait 0). Use --keywords and --classes params to provide those files to the tool.

```
make_opcodes.exe script.txt --output opcodes.txt --keywords ..\data\sa\keywords.txt --classes ..\data\sa\classes.db 
```

**Comment by MatiDragon-YT** [comment]
> do you see anything at all? flashing window, running process, any files generated (even empty). Do you run Sanny as admin?

Without running it as administrator, nothing comes out. Only SB freezes for a short moment.
And running as administrator, the Windows window appears, that a file is being copied, but when checking the opcodes file, it is not updated, and if I delete it, it is not created.

**Comment by x87** [comment]
Thanks for helping me to triage this issue. I think I found the root cause. Please stay tuned, should be resolved with the next update.

**Comment by x87** [comment]
@MatiDragon-YT please check version 3.8.2 and confirm the fix

**Comment by MatiDragon-YT** [comment]
@x87 It works very well 👍
