### ISSUE TITLE
bug in the constants

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#190]
Sanny does not replace variable constants that are used as arrays.

![image](https://user-images.githubusercontent.com/43966706/162330384-eb080e7b-7d9a-425f-b754-1133c677f781.png)

**Comment by MatiDragon-YT** [comment]
It only compiles successfully, if you manually replace the constants with their values.

**Comment by MatiDragon-YT** [comment]
It also fails this way, along with the highlighter.

![image](https://user-images.githubusercontent.com/43966706/162348038-83ceff7d-2bfc-46ca-bd45-c36875f1b56b.png)

**Comment by x87** [comment]
this page describes that limitation and a workaround: https://docs.sannybuilder.com/coding/constants#limitations

**Comment by MatiDragon-YT** [comment]
I see... so you could support this?
And while thinking about whether to give it or not, may I suggest documenting the case of local variables.

**Comment by x87** [comment]
fixed in 3.9.0
