### ISSUE TITLE
How to Compile Cleo File Full details For SB Android

### ISSUE THREAD

**Issue by AllrounderBapu** [sannybuilder/dev#191]
Hello, Sanny Builder Author
I Am Creating SB For Android Gta Sa Moding
I need to know Cleo Compile System please share
Full details Like Before Compile Cleo File What Prosses I create One App for Android
please Help me
[My YouTube](https://www.youtube.com/c/AllrounderBapu07) 
Thankyou, SB Team

**Comment by x87** [comment]
You can find a plenty of information for your needs on the following pages:

https://gtamods.com/wiki/SCM_language
https://gtamods.com/wiki/Opcode
https://github.com/thelink2012/gta3sc
