### ISSUE TITLE
Pre-processing

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#194]
**Would it be possible to add a customizable code preprocessor option to the IDE?**
As another binary compiled file or not compiled as JS, where the source code must go before to be able to compile definitively.

Something like that...
Suppose we have this code in SB:
```js
new Menu($Panel, 0, 'EXAMPLE', 'CAR11', 'CAR5')

set Menu($Panel, 0, 'REPLACE', 'TEST1', 'TEST2', 'TEST3', 'TEST4')
```
This could translate to this
```js
Menu.Create($Panel, 0, 'EXAMPLE', 'CAR11', 'CAR5', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY')

Menu.SetColumn($Panel, 0, 'REPLACE', 'TEST1', 'TEST2', 'TEST3', 'TEST4', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY')
```
and then from here, be compiled by the IDE.

I remember once @x87 you said that you would like SB to be able to load plugins, this could be a simple way to start with that, although it is something simple, it can be quite practical and something that can be improved in the future.

**Comment by x87** [comment]
@MatiDragon-YT 

how exactly `new Menu($Panel, 0, 'EXAMPLE', 'CAR11', 'CAR5')` translates to `Menu.Create($Panel, 0, 'EXAMPLE', 'CAR11', 'CAR5', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY', 'DUMMY')`?

Is it an IDE extension (like CoordManager) or part of compile-time processing?
where this macros is defined (what describes how many 'DUMMY' should be inserted)?

**Comment by MatiDragon-YT** [comment]
@x87 

Excuse me, I didn't realize that I wrote the NEW and SET of the MENU class with the same functionality.
But nothing happens. The idea is to implement these functions to the compiler, as a step before being superprocessed by the IDE.

So that all your source code that you have in a tab is passed to a function, that takes care of somehow adjusting the information in it, so that it can then be processed.

![new-adapter](https://user-images.githubusercontent.com/43966706/178115157-b8bc52e4-ded5-45ea-8c9b-c0c94cba42d5.png)

It also occurred to me that a new syntax for declaring Array values, somewhat closer to the syntax of modern programming languages, could be implemented as follows:
```
$Var(0@,6i) = [213, 8364, 273, 3873, 8374, 3764]
20@($uhs,2i) = [1, 2]
```
translating to
```
0@ += 1
$Var(0@,6i) = 213
0@ += 1
$Var(0@,6i) = 8364
0@ += 1
$Var(0@,6i) = 273
0@ += 1
$Var(0@,6i) = 3873
0@ += 1
$Var(0@,6i) = 8374
0@ += 1
$Var(0@,6i) = 3764

$uhs += 1
20@($uhs,2i) = 1
$uhs += 1
20@($uhs,2i) = 2
```
to be worked on by the general compiler.

---

Here I made the adapter system in JavaScript in a simple way.
Using only the function Replace() of the Strings with RegExp and some pairs of arrays.

<details>
 <summary>Click to expand!</summary>


```js
let codeFragment = `//---# NEW ARRAY SYNTAX

$Var(0@,6i) = [213, 8364, 273, 3873, 8374, 3764]
20@($uhs,2i) = [1, 2]

//---# RANGE ATTRIBUTE

Range(0@, 0, 25)
Range($float, -23.2, 3.0)

//---# MENUS AUTOCOMPLETED

set Menu($Panel, 0, 'EXAMPLE', 'CAR11', 'CAR5')
`

function ADAPTER_NEW_SYNTAX(input){

    return input
        // NEW ARRAY SYNTAX
        .replace(/(\$[\w\d_]+|\d+@)\((.+)\)([\x20\t]+)?=([\x20\t]+)?(\[.+\])/g, inputString => {
            
            let dataOfString = inputString.match(/(\$[\w\d_]+|\d+@)\((.+)\)([\x20\t]+)?=([\x20\t]+)?(\[.+\])/)
            dataOfString[2] = dataOfString[2].split(',')
            dataOfString[5] = dataOfString[5].replace(/(\s|\[|\])/g,'').split(',')

            let newFragment = ""

            dataOfString[5].forEach(inputElement => {
                newFragment += `${dataOfString[2][0]} += 1\n${dataOfString[1]}(${dataOfString[2][0]},${dataOfString[2][1]}) = ${inputElement}\n`
            })

            return newFragment
        })
        
        // RANGE ATTRIBUTE
        .replace(/Range\((.+),(.+),(.+)\)/g,"if $1 < $2\nthen $1 = $2\nend\nif $1 > $2\nthen $1 = $2\nend\n")

        // MENUS AUTOCOMPLETED
        .replace(/set Menu\(.+\)/g, inputString => {
            let dataOfString = inputString.match(/set Menu\((.+)\)/)

            let p = dataOfString[1].split(',')
            
            while(p.length < 15){
                p.push("'DUMMY'")
            }

            let c = 0

            let newFragment = `08DB: set_panel ${p[c++]} column ${p[c++]} header ${p[c++]} data ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]} ${p[c++]}`

            return newFragment
        })
}

//----------

console.log(ADAPTER_NEW_SYNTAX(codeFragment))
/* output
//---# NEW ARRAY SYNTAX

0@ += 1
$Var(0@,6i) = 213
0@ += 1
$Var(0@,6i) = 8364
0@ += 1
$Var(0@,6i) = 273
0@ += 1
$Var(0@,6i) = 3873
0@ += 1
$Var(0@,6i) = 8374
0@ += 1
$Var(0@,6i) = 3764

$uhs += 1
20@($uhs,2i) = 1
$uhs += 1
20@($uhs,2i) = 2


//---# RANGE ATTRIBUTE

if 0@ <  0
then 0@ =  0
end
if 0@ >  0
then 0@ =  0
end

if $float <  -23.2
then $float =  -23.2
end
if $float >  -23.2
then $float =  -23.2
end


//---# MENUS AUTOCOMPLETED

08DB: set_panel $Panel column  0 header  'EXAMPLE' data  'CAR11'  'CAR5' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY' 'DUMMY'
*/
```


</details>

I don't know if I made myself clear with all this, but I hope it is understood that the idea is not to make a new macro system, but to make the IDE able to interpret new syntaxes.

**Comment by MatiDragon-YT** [comment]
I pass all the ideas to separate tikets.
