### ISSUE TITLE
Unknown model ID

### ISSUE THREAD

**Issue by SIKAndar456321** [sannybuilder/dev#199]
Compiled file has no header, so the model name #PGA can not be used. Use number ID instead.

plz help
![image](https://user-images.githubusercontent.com/111359759/184877813-dd47b96f-769a-4d3d-965d-1552be0321d1.png)

**Comment by x87** [comment]
the compiler does not know that #PGA is. Either provide a path to the game directory in options so it can scan IDE files and find the id, or use the id number instead of #PGA

**Comment by x87** [comment]
closing as inactive
