### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by d1suption** [sannybuilder/dev#203]
system: windows 8.1 x64
![image](https://user-images.githubusercontent.com/86132132/193169414-d050a5bd-131b-4cbe-80da-98a450d7ac40.png)

**Comment by x87** [comment]
This message alone isn't helpful. Can you provide more information?

**Comment by Aronakich** [comment]
> This message alone isn't helpful. Can you provide more information?

Hmm. I have windows 8.1, used to use windows 10, no errors.

**Comment by x87** [comment]
What version of Sanny Builder you have? Have you modified any files in Sanny Builder data directory? What do you do when this error occurs? Can you provide sanny.log file?

**Comment by Aronakich** [comment]
> What version of Sanny Builder you have? Have you modified any files in Sanny Builder data directory? What do you do when this error occurs? Can you provide sanny.log file?
The version is the latest, I didn't modify the files, I just ran the program. Log attached
[sanny.log](https://github.com/sannybuilder/dev/files/9733003/sanny.log)

**Comment by x87** [comment]
according to the log you run 3.8.1.6268. latest version is 3.8.2.6275

can you check 3.8.2 and if the error still occurs provide sanny.log file

**Comment by x87** [comment]
That log file is not relevant to the screenshot that you provided. The date, version and error address are not matching.

I need more information, ideally a video showing how you run sanny builder and the content of sanny.log file immediately after it

**Comment by Aronakich** [comment]
> That log file is not relevant to the screenshot that you provided. The date, version and error address are not matching.
> 
> I need more information, ideally a video showing how you run sanny builder and the content of sanny.log file immediately after it


https://youtu.be/Juy5_ddGSRw

**Comment by x87** [comment]
Can you try to install to a new directory? Some files in the existing directory might have been corrupted and even with fresh install you still use them.

**Comment by x87** [comment]
Also question: was any previous version working on Windows 8.1?

**Comment by Aronakich** [comment]
> Can you try to install to a new directory? Some files in the existing directory might have been corrupted and even with fresh install you still use them.

I tried to install it in another directory, but it didn't work. it only worked on windows 10

**Comment by x87** [comment]
I was able to reproduce a similar crash with invalid mode.xml file. Sanny was unable to display a proper message and log the error because the application was not created yet.

in my case it was invalid XML syntax. I'm not sure if the error in this ticket is related to it, but reinstalling Sanny may help
