### ISSUE TITLE
min() and max() built-in commands

### ISSUE THREAD

**Issue by firedihm** [sannybuilder/dev#208]
This is a request to add min() and max() built-in commands. It would receive 3 arguments and would store min/max of two values into the third one.

Some examples:
```
0@ = rand(1,5)
1@ = rand(1,5)
if 0@ > 1@
then 2@ = 1@
else 2@ = 0@
end
```
```
0@ = rand(1,5)
1@ = rand(1,5)
min(2@, 0@, 1@)
```

Should also work with only 2 unique vars
```
0@ = rand(1,5)
1@ = rand(1,5)
if 0@ > 1@
then 0@ = 1@
end
```
```
0@ = rand(1,5)
1@ = rand(1,5)
min(0@, 0@, 1@)
```

Maybe even:
```
0@ = rand(1,5)
1@ = rand(1,5)
2@ = min(0@, 1@)
```

**Comment by x87** [comment]
can be implemented with #206
