### ISSUE TITLE
Add also "--decompile" parameter to CLI

### ISSUE THREAD

**Issue by strejda603** [sannybuilder/dev#214]
Hello!

Enjoying your new CLI syntax!

It would be nice, if there could be also "--decompile" parameter (if it doesn't exist already), so I could specify output path and bypass confirmation (maybe with -y/-n option) of "This script contains its original source code" message.

Like this:
```sanny.exe --decompile -y "input_file_path" ["output_file_path"]```

Thank you!

**Comment by x87** [comment]
Makes sense, thanks for the suggestion!

**Comment by x87** [comment]
https://docs.sannybuilder.com/editor/cli#decompile
