### ISSUE TITLE
Issue in Re-compiling main.scm of GTA SA v1.0

### ISSUE THREAD

**Issue by soujikun365** [sannybuilder/dev#216]
- Operating System: Windows 10 IoT Enterprise LTSC 2021 x64
- Sanny Builder's Version: https://github.com/sannybuilder/dev/releases/download/v3.8.4/SannyBuilder-v3.8.4.exe
- GTA SA's Version: GTA SA 1.0 US HOODLUM 14383616 bytes

Hello! I decompiled original main.scm of GTA SA with Sanny Builder then compiled the file again without modifying anything, but SB returned a compiler error "Unknown directive fading." at line 075296 as below:
![Error 1](https://user-images.githubusercontent.com/125864006/220063791-84007126-a83f-4062-9c7b-a8ce431457c4.png)

I tried re-installing both Sanny Builder and GTA San Andreas, but the problem still persists.

Some of my settings in SB
![Settings](https://user-images.githubusercontent.com/125864006/220072083-21670fc1-346d-4d3e-a0ff-99cb217b5e2c.png)

Original main.scm and script.img of the game
[script (original).zip](https://github.com/sannybuilder/dev/files/10782819/script.original.zip)

script folder when the issue arose
[script.zip](https://github.com/sannybuilder/dev/files/10782837/script.zip)

**Comment by x87** [comment]
Thank you for reporting this problem. This bug was introduced in v3.8.3

**Comment by x87** [comment]
Fixed in 3.8.5
