### ISSUE TITLE
Auto complete ignores name text case

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#219]
Auto complete feature (Ctrl + Space) displays and inserts everything as lower case.
Currently my "Case converting" option in settings is set to "As is".

**Comment by x87** [comment]
Can you show an example? What do you mean by "everything"? Keywords, variables, labels?

**Comment by MiranDMC** [comment]
const
    Keyboard_Cooldown = 200 // ms between keyboard presses
end

Is presented and inserted as "keyboard_cooldown"

**Comment by x87** [comment]
Labels should appear as you type @

**Comment by MiranDMC** [comment]
Uh right. So labels have correct case. So seems like problem is related to constants names only.
