### ISSUE TITLE
Crash program 

### ISSUE THREAD

**Issue by memejames** [sannybuilder/dev#222]
Wherever I create a new file the program crashes on exagear, Please Help

**Comment by x87** [comment]
Not enough information. Provide more details: screenshot, logs, steps to reproduce, etc.

**Comment by MatiDragon-YT** [comment]
@memejames exagear is only compatible up to sanny builder 3.3.3.

**Comment by x87** [comment]
What is exagear and why it works only with 3.3.3?

**Comment by MatiDragon-YT** [comment]
> @x87 :
> What is exagear and why it works only with 3.3.3?

Exagear is a emulator of Windows XP o 98, powered by the engine of Wine for Android.

This only supports up to SB 3.3.3, why you said you would no longer support it, for these outdated Windows.

I remember asking you once if it wasn't possible to keep SB running on these older operating systems, limiting access to features that require more up-to-date Windows, why so many users were using Android for make mods, and you answered with a "No." ".  I also asked you if you could make an SB3 for Android and you told me that you didn't know how to make applications for it or something like that.
