### ISSUE TITLE
allow to set destination param outside of parentheses

### ISSUE THREAD

**Issue by firedihm** [sannybuilder/dev#234]
opcodes that return values could have their destination param written before class.proc(), like this
```
var0 = Memory.Read(addr, DWORD, false)
```
this can work similarly to class instancing feature, where class instance just replaces first param of an opcode; maybe even in union with it:
```
var0 = $PLAYER_CHAR.StoreCarIsInNoSave()
```

**Comment by x87** [comment]
You can do it by updating method definition in classes.db to

```
^Read,[0A8D,=,2,0,0],("result%i" "address%i" "size%i" "vp%b")
```
