### ISSUE TITLE
Include Examples of High-Level Constructs in help\examples\

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#24]
The original idea was to restore some of the example scripts included with Cleo3 because I found the showsavescreen script to be particularly useful as an example of a high-level construct. I've since reworked this script to be more sensitive to keystrokes and to use as a template for other basic trigger scripts.

[F4SaveScreen.txt](https://github.com/sannybuilder/dev/files/4206711/F4SaveScreen.txt)

Current MemoryHandling.txt includes the depreciated $Version directive.

**Comment by Zarkong** [comment]
I uploaded 15 Cleo scripts in high level for GTA SA and I wrote a Tutorial that explains Newbies the Syntax of HighLevel

Run the highlevel.htm inside zip to read it

7 Tuto_Scripts are part of of the tut and are explained in highlevel.htm
8 other Example_Scripts are explained in readme.txt

______________________________________________________________

ZAZ, Homepage:	www.zazmahall.de/index.htm

**Comment by x87** [comment]
Wow, cool, thanks to you both, I will take a look.
