### ISSUE TITLE
SAGXT.text Missing Entries and Tables

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#25]
It was brought to my attention that the 3.3.3 version of SAGXT.text is missing the entry for FEM_OK that used to be included in older versions. The Public version appears to be the same. The two files are so different that it's not easy to compare the files for issues with other entries.

The entries are no longer sorted into their GXT tables. This makes this file considerably less useful than previous versions.

I'm not sure when the files changed or why.

**Comment by x87** [comment]
I got this file from @ThirteenAG. I believe he was working on a side project and updated many previously unknown hashes. The update was also done for GTA 3 and VC.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/GTA-One-Liners/blob/master/plugins/data/text/GTASA.text
I have FEM_OK here, but it might be possible this is a newer file.

> The entries are no longer sorted into their GXT tables. This makes this file considerably less useful than previous versions.

I didn't have the use for GXT tables and they'd make the file harder to parse, so I got rid of them.
That's why I asked to keep old files here http://public.sannybuilder.com/GXT/old/
Because mine are a bit different.

**Comment by OrionSR** [comment]
Thanks AG. The file you linked looks much more complete than the version included with v3.3.3. Still, without the table references it's going to frustrate a lot of people when they don't work. Sanny's public documents are not well known to general users; maybe the older file should be included in the release files.

For reference, the issue was discovered when ZAZ was trying to answer a [question on checking if a GXT entry was valid](https://gtaforums.com/topic/951434-gxt-entry-exists/). I'm not sure what he had in mind but I worked out something that can do the job, but it will have problems if the strings are too long.

Is there a max limit for the string length?

**Comment by x87** [comment]
>Is there a max limit for the string length?
the limit to the string length in a GXT file is 2047.

**Comment by OrionSR** [comment]
https://github.com/Sergeanur/GXT/blob/master/SA%20PC/americanMission.txt

Serge's GXT text reference. Includes reference for tables. Not sure how it compares to the list from ThirteenAG.

**Comment by x87** [comment]
I'm bringing back old GXT files with 3.4.0
