### ISSUE TITLE
Change Hotkeys for InstaSearch

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#26]
Currently [Instasearch](https://docs.sannybuilder.com/features#instasearch) uses Ctrl+Num[2,4,6,8] combos. The Num keys are hardly available on laptops that makes this feature unusable.

Proposal: change hotkeys to Ctrl+ArrowUp/Down/Left/Right. Deprecate old combos, keep for a couple versions then remove.

**Comment by x87** [comment]
Need to support functions
https://docs.sannybuilder.com/coding/data-types#labels

**Comment by wmysterio** [comment]
I would like to be able to bind all available keys. After "Visual Studio" I automatically press "F5" to compile instead of "F6 / F7"))

**Comment by x87** [comment]
@wmysterio good point. I added F5-F8 to options. Can't make all hotkeys customizable at this moment as I'm wrapping up the release, but I will be making more hotkeys customizable in the future.

**Comment by x87** [comment]
InstaSearch is called "Navigate to Symbol" in v3.8.0 This function has been changed from the previous releases. 

The default combo is Alt+Right.
If the cursor is under a label or a mission name (as in `0417: start_mission MISSION_NAME`), or a function (`my_func()`) IDE will navigate to the label (or the mission/function first line of code).

The default combo to return back to the previous location is Alt+Left. Sanny Builder supports deep navigation (Navigate to one label, then to another, and so on and so forth), and returning back to previous locations.

In the future I want to expand this feature to be able to navigate to other points of interest, for example from the constant or variable name to the declaration.
