### ISSUE TITLE
BUG: arithmetic operations - no suported

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#280]
SB4 is not compiling operations where it is indicated on the same line that it is an INT or FLOAT operation.

![image](https://github.com/sannybuilder/dev/assets/43966706/108fc9da-65b6-4e55-b26e-a335ab0e10b0)

**Comment by x87** [comment]
This is correct behavior. You can only use `int` with assignment ('=')
https://docs.sannybuilder.com/coding/variables#variable-initialization

**Comment by x87** [comment]
In your example last line can be written without int

```
1@ *= -1
```

**Comment by MatiDragon-YT** [comment]
Wait... you're telling me that what I was using was a bug? whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaatttt
