### ISSUE TITLE
BUG: tabs attacheds

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#281]
Sanny Builder is not correctly selecting the tab where a syntax error is found. This means that when we fix our error, and select the main edit file, it cannot be selected.

![image](https://github.com/sannybuilder/dev/assets/43966706/4d97afbc-0203-437d-acfc-e74cfb7a2f43)

**Comment by x87** [comment]
fixed in 4.0.0-alpha.1
