### ISSUE TITLE
BUG: incorrectly compiled dynamic classes

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#282]
I don't really know the name of this class method, which can be used in the following way:
```
if Actor.Model(_Player) == 0@
[....]
Actor.Model(_Player) = 0@
[....]
0@ = Actor.Model(_Player)
```
look how the `Actor.Model` method is used for different things... anyone would say that they are well written, but I don't know what happens to SB4 that doesn't compile them correctly and makes that if you run into any of these lines, it closes the game.

**Comment by x87** [comment]
try with this [core.zip](https://github.com/sannybuilder/dev/files/13196973/core.zip)

**Comment by MatiDragon-YT** [comment]
runing with't problem! Epic :D
