### ISSUE TITLE
Cannot see the folder with the script created

### ISSUE THREAD

**Issue by FarmerKarwer** [sannybuilder/dev#292]
I'm using the latest version of Sanny Builder on Windows 11.

I created a new folder "scripts" within SB and saved my script in this folder:

![image](https://github.com/sannybuilder/dev/assets/83603595/e34eaef3-fa81-4a85-ae54-a37247ff7bae)

However, when I open SB folder via File Explorer, I don't see the folder with my script:

![image](https://github.com/sannybuilder/dev/assets/83603595/849a288f-d0cc-459a-af2e-bea37ec0f3ae)

In Advanced settings, I selected "Show hidden files, folders, and drives", but it did not help me.

P. S. The path is identical in both cases.

P. P. S. Also, I don't see my script in cmd

![image](https://github.com/sannybuilder/dev/assets/83603595/81131f04-37f9-4b34-9103-8adab6326f4f)

**Comment by FarmerKarwer** [comment]
The issue is solved simply by opening Sanny Builder as administrator.

But it would be great to add this issue and solution to documentation, so nobody could have such problems.

**Comment by x87** [comment]
https://github.com/sannybuilder/dev/issues/43

Can be avoided by installing Sanny in a folder different from C:\\Program Files (x86)
