### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#3]
Explore a possibility to implement a dark theme for the IDE

**Comment by wmysterio** [comment]
If a dark theme can be implemented, it might be worth adding a theme editor or theme setup files? For each person can be create personal theme :)

**Comment by MatiDragon-YT** [comment]
with clear icons as i mentioned a day before? https://sannybuilder.com/forums/viewtopic.php?id=5529

**Comment by x87** [comment]
![sanny-dark-mode](https://user-images.githubusercontent.com/5698288/107130973-9fccfe80-68a0-11eb-9452-514b31bf6b0c.PNG)

thoughts?

**Comment by x87** [comment]
https://github.com/sannybuilder/themes - a new repo for theme customizations

**Comment by wmysterio** [comment]
> thoughts?

Nice! I am experimenting with a color scheme too. So far it turned out like this (the colors are from the material design):

![](https://i.ibb.co/fvttkdD/image.png)

I would like to see highlighting for enums, a separate color for gosub commands (`TEST()`), and so that keywords are not highlighted if they are used in the opcode (`0A93`).

**Comment by VitalRus95** [comment]
Well, I see now everyone shows their variants of a dark theme, so I'll join:
![изображение](https://user-images.githubusercontent.com/73489604/118686083-5b8cbb00-b80c-11eb-970e-36dedc5ad4c3.png)
What I would like to have in a dark mode is a dark UI of the whole programme, not only in the code part of the window. Yet the idea of having a theme choice is great and refreshing, since it is now rare to find a programme that has more than one or two visual styles.

**Comment by x87** [comment]
@VitalRus95 
>dark UI of the whole programme, not only in the code part of the window

that would be cool, but there are some limitations. I can make the bottom toolbar customizable and the area with line numbers (I made the font color here the same as the primary font of the editor). But the main panel with icons and the scrollbar area is hardly customizable at this point. Also re-coloring the main panel would require a new set of icons (white)

**Comment by VitalRus95** [comment]
@x87 
> I can make the bottom toolbar and the area with line numbers customizable
I didn't notice it at first on your screenshot. Looks nice to me! And what do you think about adding some custom themes to future versions of SB as default options? I think that may motivate people to be creative and follow SB development closer. Of course if it won't be difficult to set up. In any case, good luck! I like that SB is being developed further! :)
P. S. I have sent you an email some time ago, could you check it, please? There's nothing urgent but still.

**Comment by x87** [comment]
>And what do you think about adding some custom themes to future versions of SB as default options? I

sure. I already created a repo for custom themes. My variation of Dark Theme is there
https://github.com/sannybuilder/themes

> I have sent you an email some time ago, could you check it, please? There's nothing urgent but still.

sent where? mail@sannybuilder.com? I haven't received any emails recently, maybe some issue with the mailbox, I will check. Meanwhile you can drop me a message on discord Seemann#6676

**Comment by VitalRus95** [comment]
@x87 
> sent where? mail@sannybuilder.com
Yes, I used this address. Maybe the message got lost, I may send it again in Discord, thanks for this option!

**Comment by MatiDragon-YT** [comment]
Was I late to show my variant?

![Screenshot_20210527-102744-291](https://user-images.githubusercontent.com/43966706/119834671-8b0b8980-bed6-11eb-86a2-b4babda64ad0.png)

**Comment by x87** [comment]
Great color schemes out there! 

I'm planning to release first v3.8 alpha sometime soon, it has a built-in theme editor, so you can play around and save your themes in the newer format. I will be waiting for your submissions in https://github.com/sannybuilder/themes

All themes will be included in the v3.8 release.

**Comment by MatiDragon-YT** [comment]
Here is my color theme and the translation of the `spanish.ini` <3

[tema-molon-xdxdxd.zip](https://github.com/sannybuilder/dev/files/6595554/tema-molon-xdxdxd.zip)

**Comment by x87** [comment]
> 
> 
> Here is my color theme and the translation of the `spanish.ini` <3
> 
> [tema-molon-xdxdxd.zip](https://github.com/sannybuilder/dev/files/6595554/tema-molon-xdxdxd.zip)

Thank you 👍

**Comment by x87** [comment]
@VitalRus95 @MatiDragon-YT @wmysterio 

Updated https://github.com/sannybuilder/themes to showcase some of your awesome contributions. Thanks!

**Comment by babab4757** [comment]
how can i put the theme?

**Comment by x87** [comment]
> how can i put the theme?

Are you asking how to USE the theme in Sanny Builder, or how to contribute a new theme?

**Comment by babab4757** [comment]
> > how can i put the theme?
> 
> Are you asking how to USE the theme in Sanny Builder, or how to contribute a new theme?

i am asking how to put that theme in sanny builder, im new and i do not now how i can use it too :(

**Comment by x87** [comment]
You need to download and install the latest Sanny Builder from here https://github.com/sannybuilder/dev/releases

3.8.0-alpha.3 includes all themes, you just need to choose one in the Options->Editor
https://docs.sannybuilder.com/options/editor#color-theme

**Comment by babab4757** [comment]
but cant i download and use any themes?

> You need to download and install the latest Sanny Builder from here https://github.com/sannybuilder/dev/releases
> 
> 3.8.0-alpha.3 includes all themes, you just need to choose one in the Options->Editor
> https://docs.sannybuilder.com/options/editor#color-theme

but cant i download and use any themes?

**Comment by babab4757** [comment]
oh yes, nevermind i found out how. it is really nice and thank you for helping me bro <3 👍
