### ISSUE TITLE
Variable declaration and assigment in one line not working

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#308]
This code will compile and work as expected:
``` 
int data
data = read_memory 0x... {size} 4 {vp} true
```

Line below will compile, but arguments order is invalid.
``` 
int data = read_memory 0x... {size} 4 {vp} true
```
**read_memory** will throw error about accessing address 0 (seems like **data** becomes first argument).

**Comment by x87** [comment]
can you attach a compiled .cs file?

**Comment by MiranDMC** [comment]
> what edit mode are you using?

GTA SA 1.0 SBL

**Comment by MiranDMC** [comment]
Hm seems be more complicated scenario. When extracted to simple test it does not compile at all:

```
{$CLEO .cs}
nop

define function PATCH_CAR_COLORS()

wait 0
PATCH_CAR_COLORS()

terminate_this_custom_script


function FOO()
    int addr = read_memory 0x00447097 {size} 4 {vp} true
    print_formatted_now {fmt} "ADDRESS %X" {time} 20000 {arg} addr
    cleo_return
end
```

**Comment by MiranDMC** [comment]
I was not able to reproduce the problem in small test scripts. Seems like caused by other mistakes during project conversion to SBL mode.
