### ISSUE TITLE
Add function name to error message

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#316]
Please add function name to the error message:
![image](https://github.com/sannybuilder/dev/assets/11084446/edc9f64f-b9b6-4cba-9cf8-65c3159c4e52)
In case if user forget function ending `end` keyword somewhere the whole code becomes one big function. Then any return call will throw mentioned error causing confusion and giving no further clues what's wrong.

**Comment by x87** [comment]
fixed in 4.0.0
