### ISSUE TITLE
Feature: constants in HEX block

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#324]
Please add support of constants in HEX blocks, like:
```
const foo = 12

hex
    00 11 foo 33 foo
end
```

Use like that would always insert 4 bytes if value was integer or float. In case of text constants included should be all its characters (without terminator string)

**Comment by x87** [comment]
constants are ambiguous. consider this example:

```
const a = 5 
hex
a
end
```

5 or 10 (0xA)?

**Comment by x87** [comment]
See #261

**Comment by MiranDMC** [comment]
Duplicate of #261
