### ISSUE TITLE
Sanny Builder Library

### ISSUE THREAD

**Issue by arbaabgtamods** [sannybuilder/dev#333]
anyone tell me how to add extra audio in gta vc i mean how to add extra voices so i can use in sanny builder plzz tell me !

**Comment by x87** [comment]
please use our Discord or GitHub Discussions board for coding related questions.
https://sannybuilder.com/discord
https://github.com/sannybuilder/dev/discussions

**Comment by arbaabgtamods** [comment]
> please use our Discord or GitHub Discussions board for coding related questions. https://sannybuilder.com/discord https://github.com/sannybuilder/dev/discussions

Sir but  i dont have discord account plzz you will ask your servers my Question ! plzz and tell me answer !
