### ISSUE TITLE
Every new update you guys doing it worse than ever

### ISSUE THREAD

**Issue by Samthapa76** [sannybuilder/dev#337]
i try to create ped and its own stuff give it error WOW what a wasting time better you retired and go fishing
https://imgur.com/9Ij3pNd

**Comment by levirrd** [comment]
Instead of being toxic, you can just look at the opcode.
Char mafia = Char.Create(7, #MAFBOSS, x, y, z)
I'm sure you're able to set the x,y,z coordinates because they are floats. :)
