### ISSUE TITLE
Making the Find option more useable

### ISSUE THREAD

**Issue by levirrd** [sannybuilder/dev#350]
I think the Find feature in SannyBuilder could be improved. Instead of only finding the first or last result, it should display all matches at once. You could navigate through them by pressing Enter, and exit the search by pressing Esc or clicking "X." Additionally, rather than opening a separate window when you press CTRL+F, the search bar could be integrated directly into the interface, similar to how browsers or Visual Studio Code handle it. This way, you could easily change search filters within the same space.
![image](https://github.com/user-attachments/assets/e71417e0-ba1e-4891-af79-acbe68445564)

**Comment by x87** [comment]
F3
