### ISSUE TITLE
Change parameters in CLI to more common syntax with dashes

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#42]
`--game` to select the default mode for the given game

`\sa` => `--game sa`, `-g sa`
`\vc` => `--game vc`, `-g vc`
`\gta3` => `--game gta3`, `-g gta3`
`\lcs` => `--game lcs`, `-g lcs`
`\vcs` => `--game vcs`, `-g vcs`
`\sa_mobile` => `--mode sa_mobile`, `-g sa_mobile`

`--mode` to select a mode by ID (each mode has an ID attribute previously known as `shortcut`)

`\debug` => `--debug`
`\compile input_file_path [output_file_path]` => `--compile "input_file_path" ["output_file_path"]`
`\nosplash` => `--no-splash`

new:

`-x "games.xml path"` #15 

Also see #14

**Comment by x87** [comment]
Old names will be kept for backward compatibility with third-party tools.

**Comment by wmysterio** [comment]
Будут ли отдельные режимы для `\SA` и `\SA SRC`? Так и не понял можно ли использовать эти параметры отдельно от настроек `games.xml`.

**Comment by x87** [comment]
@wmysterio you should be able to switch to any edit mode defined in the games.xml using `--mode`.

**Comment by wmysterio** [comment]
Thanks for new syntax in CLI! I tested the Compiling and all completed successfully:
```text
var mode = "sa"; // !!! lowercase (by default)
var params1 = $"--mode {mode} --no-splash --compile \"{inputTxtFile}\" \"{mainScmFile}\"";
var params2 = $"-m {mode} --no-splash -c \"{inputTxtFile}\" \"{mainScmFile}\"";
startSB( sannyExe, params1 ); // OK
startSB( sannyExe, params2 ); // OK
```
