### ISSUE TITLE
Can use constants in `quotation mark`?

### ISSUE THREAD

**Issue by wmysterio** [sannybuilder/dev#50]
Hey. Maybe should use quoted constants? For example:
```text
`CONST_A` = 20.0
`CONST_B` = 0@
015D: set_gamespeed `CONST_A`
015D: set_gamespeed `CONST_B`
```
A regular expression should be find faster than full code analysis. When enter the `@` character, it finds all labels; and when enter a quotation mark, can also search for constants. And it will be easier to highlight them.

**Comment by x87** [comment]
Those are called backticks: https://en.wikipedia.org/wiki/Grave_accent

Thanks for your idea, but I would not want to introduce another syntax element just to help IDE find those constants. We have enough obscure symbols all over the place ($, @, #, &, etc) so adding more make the language harder to learn and use.

**Comment by x87** [comment]
related to #28
