### ISSUE TITLE
Textbox from "Ini path" option is blank (3.5.0).

### ISSUE THREAD

**Issue by wmysterio** [sannybuilder/dev#55]
Hello. "Ini path" option have blank textbox always and button about him is not clickable. It necessary or it a bug?

**Comment by x87** [comment]
This is expected. This option is unused #51 

I haven't decided if I want to remove this element completely or re-use for something different, for example Copy directory setting #48

**Comment by wmysterio** [comment]
Ok. I will test compiling modes. I have problem with `--` syntax. Old syntax work.

**Comment by x87** [comment]
Old syntax is kept for backward compatibility. Please report any issues you find here #42
