### ISSUE TITLE
New features for the Editor/IDE

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#60]
# Tabs Scroll
![gigg](https://user-images.githubusercontent.com/43966706/90965899-d229a180-e4a2-11ea-8590-7e993dea3f8c.gif)

**Comment by OrionSR** [comment]
I like it. I have often wanted to use such a feature. 

Tab dragging and Split Screen so I can work with two files at once are two reasons I occasionally use the 010 Editor to edit scripts with Sanny linked as an external compiler.

**Comment by MatiDragon-YT** [comment]
# Zoom into the letters.
### Increase and decrease the size of the letters
Many of us are very often changing the size of the letters and others may not, but this is something that most IDEs carry and it would be a very good thing if they included the SB.
The idea of ​​the controls for this would be the standard

* `Ctrl` + `Scroll of Mouse`

| Ctrl + | Scroll Up |Scroll Down |
| -------| ---------- |------------- |
|           | Zoom in  | Zoom out |

**Comment by OrionSR** [comment]
Sanny already has a Zoom feature implemented by another common standard, Ctrl+Plus and Ctrl+Minus. However, I was not able to find this feature listed in the Hotkey documentation or anywhere else.

In general though, I think a lot of standard features would benefit from tool bar implementation.

**Comment by MatiDragon-YT** [comment]
it is true, if it is in the documentation, with this configuration

| Text / Navigation | |
| ------------ |----- |
| `Ctrl+ScrollUp` `Ctrl+ScrollDown` | page up / down |
| `Ctrl+Num+` `Ctrl+Num-` | zoom in / out |

But there is already a button to do Page Up and Page Down, and in laptops that do not have that button, it is done with the combination of the button <Function> e.g.
* `Fn` + `ArrowUp` = Page Up
* `Fn` + `ArrowDown` = Page Down

so the current combination is a bit obsolete.
Or else, how about this other?
# Support custom controls
This would be a very useful functionality, since it allowed to adapt the tastes of the community with great comfort, so they would no longer have to use third-party programs for their projects.

**Comment by OrionSR** [comment]
Ah, I understand the problem better, thanks for clarifying. 
Issues with hotkey compatibility for Instasearch is mentioned in #26

> Support custom controls
I'm a bit worried about custom hotkeys. I've had issues #22 with the inconsistent operation of the configurable hotkey for converting models (Ctrl+Alt+H by default). It's like the previous hotkey doesn't work when I install a new version and I need to come up with another to get it working again.

@x87 I commented in #22 recently but can't figure out how to re-open the issue.

**Comment by MatiDragon-YT** [comment]
# Automatic tabs
It occurred to me that maybe I could add an "AUTO-TAB" by hitting enter at the end of each IF, THEN, ELSE, WHILE, REPEAT and FOR. Although this can also be done with macros, it would be more convenient this way.
More inf. #46

**Comment by x87** [comment]
@MatiDragon-YT please create one ticket for each suggestion. It helps to manage the scope of work between versions. also a specific title tells more than a generic "New features"
