### ISSUE TITLE
[Collaboration] Improved Spanish translation

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/dev#63]
No... it's not that I don't like the current translation, just that it looks a bit robotic, or boxy without the accents and tildes...
Please~ do't hurt me~ :''D
The thing is.. I sent this file a long, long, long time ago by mail.. but nothing happened... Sure, I think they were withdrawn due to the updates they lost... And I thought maybe now it would be a good time to contribute with a grain of sugar... 

[spanish.zip](https://github.com/sannybuilder/dev/files/5132847/spanish.zip)

**Comment by x87** [comment]
@MatiDragon-YT Thank you, I opened a pull request so you may review and make more changes in the meantime
https://github.com/sannybuilder/translations/pull/7/files

**Comment by MatiDragon-YT** [comment]
@x87  I don't know much about GitHub, but days ago I wondered if you corrected the file I sent first, [with this one](https://github.com/MatiDragon-YT/translations/blob/patch-2/spanish.ini) so it doesn't go wrong with next release plan #61

**Comment by x87** [comment]
@MatiDragon-YT I updated https://github.com/sannybuilder/translations/pull/7/files

**Comment by MatiDragon-YT** [comment]
@x87 it's MatiDragon, without the **,** at [credits](https://github.com/sannybuilder/docs/blob/ea99ab349465200d12c2bb3102bfa57a9c1bdf5d/credits.md) GG

**Comment by x87** [comment]
> @x87 it's MatiDragon, without the **,** at [credits](https://github.com/sannybuilder/docs/blob/ea99ab349465200d12c2bb3102bfa57a9c1bdf5d/credits.md) GG

it's markdown syntax for bold text. for some reason the comma was in bold. I removed it

**Comment by MatiDragon-YT** [comment]
@x87 I just got a new PC, and I took the time to update the translation for SB 3.7.0.
And....
Would you like to pass me the spanish.ini when you are about to release a new version of SB, to keep it updated?

**Comment by x87** [comment]
@MatiDragon-YT so far, https://github.com/sannybuilder/translations/blob/master/spanish.ini this is the latest translation. I don't have anything outside of it.

So you can send your update or create a pull request in the translation repo.
