### ISSUE TITLE
Handle missing modes file gracefully

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#68]
running with missing modes.xml or with an invalid path in -x crashes Sanny. need to handle gracefully (ERR_0007).

**Comment by OrionSR** [comment]
The slightest error in modes.xml also causes a nasty crash. However, with the new CLI options executed with a User Tool the process is working much better. Before I needed to restart to test a modified edit mode, now I can switch modes with the CLI while Sanny is running. As a result, the second instances (?) may crash out but Sanny keeps running, so I can keep editing while I hunt down the bug.

**Comment by x87** [comment]
after https://github.com/sannybuilder/dev/issues/74#issuecomment-1581201191 there will be multiple mode.xml files
