### ISSUE TITLE
RockStyle Commands in Templates for SA - SCR, LCS and VCS

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#70]
The template scripts for SA -SCR, LCS, and VCS modes have _community_ style command definitions. The LCS and VCS opcodes have been updated, but not the "keyword" text. I would expect a proper SA - SCR template to look something like this:
```cleo=CLEO script
={$CLEO .cs}
=0000:
=
=|
=
=0A93: terminate_this_custom_script


load=model request and load
=0247: request_model #| 
=
=while 8248:   not has_model_loaded  #
=  wait 0 ms
=end

def=Check if player is playing
=if 
=  0256:   is_player_playing $PLAYER_CHAR
=then
=  
=end

scm=Multifile template (SA)
=DEFINE MISSIONS 0
=//DEFINE MISSION {ID} 0 AT {LABEL} @
=DEFINE EXTERNAL_SCRIPTS 0 // Use -1 in order not to compile AAA script
=//DEFINE SCRIPT {NAME}  AT {LABEL} @
=DEFINE UNKNOWN_EMPTY_SEGMENT 0
=DEFINE UNKNOWN_THREADS_MEMORY 0
=
=|
=
=while true
=  wait 250
=end
```

Also, if the complete set of keyword.txt from fastman92's definitions are implemented then the opcodes can be omitted and the scripts would become more generic.

Generating templates for RockStyle commands should be the last barrier to completing my initial set of custom edit modes. I should have something available for preview soon, hopefully today.

**Comment by x87** [comment]
Good catch. Yes, we should align templates and opcode definitions.
