### ISSUE TITLE
User tools should support sanny and game path variables

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#72]
https://github.com/sannybuilder/dev/issues/6#issuecomment-695962744

**Comment by OrionSR** [comment]
Having the @sb: path work in user tools would certainly make sharing tool configurations a lot easier. I wasn't sure what to think about @game: with the path changing with the edit mode, but it might come in handy for the parameters.

May as well consider @copy:(?) as valid in user tool paths as well.

Related: I couldn't figure out how to configure <ide base=".."> as the parent directory of DAT files. Is this a limitation or did I configure it wrong? Something like @parent: should work for all standard DAT files. 

The problem with the current format is that the entry gets very long quickly, and when updating the entry for another mode I need to change the same folder name twice in the same line. This was annoying as I was setting things up but now that it's working I doubt I'll be updating the data paths very often.

**Comment by x87** [comment]
`@sb:` and `@game:` are now supported
https://docs.sannybuilder.com/features#external-tools-menu
