### ISSUE TITLE
Increased Screen Space for the Current Edit Mode

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#8]
Currently, only 12 to 14 characters can be used before the game icon becomes obscured. The just isn't enough room to spell out Liberty City Stories (20). It's difficult to describe the edit mode, platform and version in the space allowed and use more than 2 to 3 characters for the game name.

**Comment by x87** [comment]
I would still prefer to have some limit here as we have other sections in the bottom bar that should be respected as well. Can you provide a few examples of long names you are trying to accommodate?

**Comment by OrionSR** [comment]
GTA Liberty City Stories - 24 char
OSR San Andreas PS2v2 - 21
F92 Grand Theft Auto 3 - 22 

Icons for platforms would help conserve a little space for something like Xbox360.
I've been getting by with much more cryptic names.

GTA SA Xbox
OSR LCS PS2
F92 GTA3 PC

**Comment by x87** [comment]
I have increased the size of this section

![gta-lcs-edit-mode](https://user-images.githubusercontent.com/5698288/90028667-f78b0400-dc87-11ea-9d02-8d47114b61a9.png)
