### ISSUE TITLE
sb 3.6.0 Android CLEO suffix (.csa) decompilation bug

### ISSUE THREAD

**Issue by XMDS** [sannybuilder/dev#88]
When dragging the script with the .csa suffix to the sb tool, the decompilation fails.  Even if we manually choose to open the .csa script through the file option, the decompilation still fails.  The decompilation can only be done through the F5 shortcut key.  This should be a bug.  .csi has no problems.

**Comment by XMDS** [comment]
@x87

**Comment by x87** [comment]
@XMDS please update `common.dll` in your `Sanny Builder\lib` directory with the file from the attached archive. It should fix the issue. 
[common.zip](https://github.com/sannybuilder/dev/files/5541222/common.zip)

**Comment by XMDS** [comment]
> @XMDS please update `common.dll` in your `Sanny Builder\lib` directory with the file from the attached archive. It should fix the issue.
> [common.zip](https://github.com/sannybuilder/dev/files/5541222/common.zip)

I just tested it and the problem has been resolved. csa decompile successfully
