### ISSUE TITLE
The Problem When I Open Sanny Builder V3.6.0

### ISSUE THREAD

**Issue by UchihaBatuhan** [sannybuilder/dev#89]
I Am Installing The New Sanny Builder Version On My Computer, But Every Time I Open It, I Get The Sascm.Ini And Opcodes.Txt Not Found Error. I Am Leaving The Screenshots Of The Error Messages.
![1](https://user-images.githubusercontent.com/74367253/98958962-e0bcad80-2513-11eb-9d66-883c2a76b8d5.PNG)
![2](https://user-images.githubusercontent.com/74367253/98958968-e2867100-2513-11eb-8c0b-f418396fc38f.PNG)

**Comment by x87** [comment]
@UchihaBatuhan please share your `settings.ini` file from the data folder

**Comment by x87** [comment]
@UchihaBatuhan do you have any Unicode letters (non-English) in the Sanny Builder's installation path?

**Comment by UchihaBatuhan** [comment]
> @UchihaBatuhan do you have any Unicode letters (non-English) in the Sanny Builder's installation path?

Yes, There Was A Letter That Was Not In English. When I Changed It, The Problem Was Solved.
Thanks For Your Help

**Comment by x87** [comment]
Sanny is not Unicode-aware, this is a known limitation, unfortunately.
