### ISSUE TITLE
Mobile Mode Creates Cleo Folder when using Compile and Copy

### ISSUE THREAD

**Issue by OrionSR** [sannybuilder/dev#9]
This required cleo directory has not be helpful when using mobile mode.

**Comment by x87** [comment]
I guess SA Mobile mode just does not have to have Game Directory setting available (as the Stories games). There are no files read from the game directory anyway.

**Comment by x87** [comment]
CLEO directory wouldn't create if Game directory is empty.

**Comment by x87** [comment]
This now can be controlled with the new mode entry `<copy-directory type="cleo">`. If this entry is missing from the mode config (as does SA Mobile) Sanny won't copy the output file anywhere.
