### ISSUE TITLE
Allow options override via CLI

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#93]
Can make command in CLI where used concrete case converting text strings? By default compiler use the setting SB. For example:
```
-string_case upper // or lower, as is
```
It will help avoid the need to edit settings. Useful when need to use formatting text:
```
0AD0: show_formatted_text_lowpriority "Text: %d" time 2000 1 // uppercase: INCORRECT FORMAT
0AD0: show_formatted_text_lowpriority "Text: %d" time 2000 1 // lowercase: good format. But other text is always small
0AD0: show_formatted_text_lowpriority "Text: %d" time 2000 1 // as is: GOOD
```
Or is this feature already there?

_Originally posted by @wmysterio in https://github.com/sannybuilder/dev/issues/14#issuecomment-715286511_

**Comment by x87** [comment]
CLI should allow overriding Sanny's settings. Example:
```
sanny.exe -o Decompiler::AlwaysWriteOpcodes=0
```
with set the Write opcodes to off.

* Should support hot updating (when Sanny is running)
* Need to cleanup and standardize settings names

**Comment by wmysterio** [comment]
>| when Sanny is running

I had a problem with Sunny before using the CLI. If the SB process is running, the IDE opens the input file without compiling (opens as a new tab).

And after compilation, the SB process continue to work. It is necessary to forcibly abort the process in the program before a new call (Maybe this program does not allow the process to terminate on its own; need to test in detail).

**Comment by x87** [comment]
Added new `--option` parameter
https://docs.sannybuilder.com/cli#option

**Comment by x87** [comment]
Renamed some options in v3.8.0-alpha.4

Smart --> Editor::SemanticConstHighlighting
Engine::ShowProgress --> Editor::ShowProgress
Engine::ShowReport --> Editor::ShowReport
QuickGameLoading --> Editor::QuickGameLoading
Editor::LookingDepth --> Editor::ScanDistance
Lang --> Editor::Lang
Formats::HexadimalOffsets --> Decompiler::HexadimalOffsets
Formats::LabelsFormat --> Decompiler::LabelsFormat
CustomNames::CustomNamesFormat --> CustomNames::Format
